"""
app.py  —  Flask backend for CineMatch Movie Recommender
Run:  python app.py
"""

import pickle
import numpy as np
import pandas as pd
from flask import Flask, request, jsonify
from flask_cors import CORS

app = Flask(__name__)
CORS(app)   # allow the HTML file (opened directly) to call this API

# ──────────────────────────────────────────────
# Load pre-saved model artefacts
# (generated by running save_model.py once)
# ──────────────────────────────────────────────
try:
    movies     = pickle.load(open('movies.pkl',     'rb'))   # DataFrame with 'title' col
    similarity = pickle.load(open('similarity.pkl', 'rb'))   # cosine similarity matrix
    print(f"✅  Loaded {len(movies)} movies.")
except FileNotFoundError as e:
    raise SystemExit(
        f"\n❌  Missing pickle file: {e}\n"
        "    Run  python save_model.py  first to generate movies.pkl & similarity.pkl\n"
    )


# ──────────────────────────────────────────────
# Helper
# ──────────────────────────────────────────────
def recommend(movie: str, n: int = 5) -> list[str]:
    """Return top-n similar movie titles."""
    matches = movies[movies['title'].str.lower() == movie.lower()]
    if matches.empty:
        return []
    idx       = matches.index[0]
    distances = similarity[idx]
    top       = sorted(enumerate(distances), reverse=True, key=lambda x: x[1])[1 : n + 1]
    return [movies.iloc[i[0]].title for i in top]


# ──────────────────────────────────────────────
# Routes
# ──────────────────────────────────────────────
@app.route('/')
def home():
    return jsonify({'status': 'CineMatch API is running 🎬'})


@app.route('/movies', methods=['GET'])
def list_movies():
    """Return all movie titles for autocomplete."""
    titles = sorted(movies['title'].tolist())
    return jsonify({'movies': titles})


@app.route('/recommend', methods=['POST'])
def get_recommendations():
    data  = request.get_json(force=True)
    movie = (data.get('movie') or '').strip()

    if not movie:
        return jsonify({'error': 'Please provide a movie title.'}), 400

    recs = recommend(movie)
    if not recs:
        return jsonify({
            'error': f'Movie "{movie}" not found in the dataset. '
                     'Check the spelling or try a different title.'
        }), 404

    return jsonify({'movie': movie, 'recommendations': recs})


if __name__ == '__main__':
    app.run(debug=True, port=5000)
